export class AppSettings {
  public static ROSTER_VIEW_MODE_PRIMARY = 'ROSTER_VIEW_MODE_PRIMARY';
  public static ROSTER_VIEW_MODE_CLIENT = 'ROSTER_VIEW_MODE_CLIENT';
  public static ROSTER_VIEW_MODE_SUPPLIER = 'ROSTER_VIEW_MODE_SUPPLIER';
  public static ROSTER_VIEW_MODE_RESOURCE = 'ROSTER_VIEW_MODE_RESOURCE';
}
